name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World!"
      - name: Actor
        run: echo "Hello I am Abhishek!"
